app:
  DATA_FILE: 'Input/rf_api_90days.csv'
  TRAIN_TEST_SPLIT_RATIO: 0.67
  LSTM_UNITS: 4
  NUM_EPOCHS: 50
  BATCH_SIZE: 1

model_1:
  cols: ['date', 'rainfall', 'gwl']
  axis: 1
  num : 1
model_2:
  cols: ['date', 'rainfall', 'gwl', 'api']
  axis: 1
  num : 2
